### ISSUE TITLE
[mesheryctl] Move constants to client configuration file

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1022]
**Current Behavior**
`mesheryAuthToken` and `mesheryURL` are defined as constants in the `mesheryctl perf` command. Default values of both include reference to "http://localhost", assuming that the Meshery server will be locally deployed. It will often be the case the Meshery server is not deploye locally, however.

**Desired Behavior**
`mesheryAuthToken` and `mesheryURL` should be user configurable.

**Implementation / Acceptance Tests**
- [ ]  Values for these two variables should carry the same defaults that they do today (using "localhost").
- [ ]  `.meshery/mesheryctl.yaml` should serve as the Meshery Client configuration file.
- [ ]  `--ctlconfig` should be available as a persistent flag (under `perf` command and later globally under other commands) to allow users to override the these variables with alternative settings.

---
**Additional Context**
See discussion - https://github.com/layer5io/meshery/pull/1021/files/27dac1d18b235b59b39293ba111109a830ab4aff#diff-13173ea6e90ec366fe2b4d11e1cba8faR37

**Comment by nitishm** [comment]
@leecalcote 
These are all the constants defined in `mesheryctl` at the moment. Plan is to move them into the mesheryctl.yaml config file

Let me know how you wish to structure this or do we keep it the way I pasted below:
```yaml
dockercompose:
  defaults:
    webURL: "https://api.github.com/repos/docker/compose/releases/latest"
    version: "1.24.1/docker-compose"
  BinaryURL: "https://github.com/docker/compose/releases/download/"
  BinaryPath: "/usr/local/bin/docker-compose"
auth:
  tokenURL: "http://localhost:9081/api/gettoken"
perf:
  url: "http://localhost:9081/api/load-test-smps?"
```
