### ISSUE TITLE
[mesheryctl] cli should allow user to add meshes for which they want mesh management

### ISSUE THREAD

**Issue by nikita15p** [layer5io/meshery#1433]
**Current Behavior**

Currently it downloads all the mesh adapter supported by meshery. 

**Desired Behavior**

It should allow user to provide mesh names through mesheryctl so that they do not endup downloading all of them which is not required. Also the flag can be optional, if no value is provided by user it can default to all.

---
**Resources**
NA

**Alternatives / Additional Context**
NA

**Comment by mgfeller** [comment]
Hi @nikita15p, thanks for raising this issue, as was also discussed at yesterday's Meshery Development Meeting (my line was quite bad so I didn't catch all that was being said). I'm looking forward to this feature as well. In the meantime, I just edit the configuration file `./meshery/meshery.yaml` (see example below), following https://meshery.layer5.io/docs/guides/multiple-adapters#configuration-running-fewer-meshery-adapters. 

-----
```
version: '3'
services:
  meshery:
    image: layer5/meshery:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - "SAAS_BASE_URL=https://meshery.layer5.io"
      - "ADAPTER_URLS=meshery-consul:10002"
#      - "ADAPTER_URLS=meshery-istio:10000 meshery-linkerd:10001 meshery-consul:10002 meshery-octarine:10003 meshery-nsm:10004 meshery-cpx:10008 meshery-osm:10010"
      - "EVENT=mesheryLocal"
    volumes:
      - $HOME/.kube:/home/appuser/.kube:ro
    ports:
      - "9081:8080"
  # meshery-istio:
  #   image: layer5/meshery-istio:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10000:10000"
  # meshery-linkerd:
  #   image: layer5/meshery-linkerd:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10001:10001"
  meshery-consul:
    image: layer5/meshery-consul:stable-latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "10002:10002"
  # meshery-octarine:
  #   image: layer5/meshery-octarine:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10003:10003"      
  # meshery-nsm:
  #   image: layer5/meshery-nsm:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10004:10004"
  # meshery-cpx:
  #   image: layer5/meshery-cpx:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10008:10008"
  # meshery-osm:
  #   image: layer5/meshery-osm:stable-latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - "10010:10010"
  watchtower:
    image: v2tec/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
volumes:
  meshery-config:
```
