### ISSUE TITLE
[mesheryctl] Unable to create context without creating local with it when user doesn't have config file

### ISSUE THREAD

**Issue by anirudhjain75** [layer5io/meshery#2162]
**Issue**: _`context create <name>` not allowed without creating `local`, too.
**Scenario**: _Config file not present. User attempts to create a named context._
**Status**: ✖️ `create` forces user to create `local` in addition to their named context.

**Case 1:**
```
$ mesheryctl system context create test
Missing Meshery config file.
Create default config now? [y/n]: n
Provide config file location using `--config <config-file>` or run `mesheryctl system context create <name>` to generate a config file.
$ cat ~/.meshery/config.yaml
cat: /Users/lee/.meshery/config.yaml: No such file or directory
```

**Case 2:**
```
➜  mesheryctl git:(context-commands) ✗ ./mesheryctl system context create test
Missing Meshery config file.
Create default config now? [y/n]: y
Default config file created at /Users/lee/.meshery/config.yaml
Added test context and set as current context
➜  mesheryctl git:(context-commands) ✗ cat ~/.meshery/config.yaml
contexts:
  local:
    endpoint: localhost:9081
    token:
      name: Default
      location: /Users/lee/.meshery/auth.json
    platform: ""
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-nginx-sm
  test:
    endpoint: https://localhost:9081
    token:
      name: ""
      location: ""
    platform: ""
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-nginx-sm
current-context: test
```

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/issues/2104#issuecomment-751966036_
