### ISSUE TITLE
[mesheryctl] support -c/--context in `system reset` command to temporarily override the current context

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2285]
#### Current Behavior

Currently while running `mesheryctl system reset`, it automatically pulls the `docker-compose.yaml` file corresponding to the `current-context` mentioned in the `~/./meshery/config.yaml` file. Example-

```
contexts:
   local:
	endpoint: http://localhost:9081
	token: local-token
        platform: docker
        adapters: 
           - istio
           - linkerd
       channel: stable
       version: v0.4.20
   prod-us-east-1:
	endpoint: http://fiwaf-ssfdd.aws.useast1.amazon.com
	token: production-token
        platform: kubernetes
        channel: edge
        version: v0.4.27
current-context: prod-us-east-1
```

Now running `mesheryctl system reset` will automatically pull the latest `docker-compose.yaml` file from GitHub since the `channel` is `edge` based on the `current-context` which is `prod-us-east-1`.

#### Desired Behavior

Instead, the `system reset` command should also support overriding the current context with a `--context`, `-c` flag. 

So, for the above example, if we run `mesheryctl system reset -c local`, it should pull the `docker-compose.yaml` file from the `v0.4.20` release(since the `local` context uses the `stable` channel with version `v0.4.20`) instead pulling the latest file.
