### ISSUE TITLE
[mesheryctl] Bug: version in config.yaml file is not validated

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2294]
#### Description

You can have invalid versions as shown below(`version: bob`) in the `config.yaml` file. 

```
user@computer:~/.meshery$ cat config.yaml
contexts:
  local:
    endpoint: http://localhost:9081
    token:
      name: Default
      location: auth.json
    platform: docker
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-nginx-sm
    channel: stable
    version: bob

current-context: local
tokens: {}
```

This can break commands like `mesheryctl system reset` which will try to pull the `docker-compose.yaml` file from the specified `version` in GitHub-

```
user@computer:$ mesheryctl system reset -c local
Meshery config file will be reset to system defaults. Are you sure you want to continue [y/n]? y
Meshery resetting...

Current Context: local
Channel: stable
Version: bob

Fetching default docker-compose file at version: bob...

...Meshery config (/home/user/.meshery/meshery.yaml) now reset to default settings.
user@computer:$ 
```

That version does not exist and [GitHub throws a 404 error](https://raw.githubusercontent.com/layer5io/meshery/bob/docker-compose.yaml). Which is missed by our current error handling function and the meshery.yaml file will be like this-

![Screenshot from 2021-01-25 14-37-09](https://user-images.githubusercontent.com/49474499/105684369-ddce3800-5f1a-11eb-851b-7927a471b639.png)

This is because it actually tries to pull the file https://raw.githubusercontent.com/layer5io/meshery/bob/docker-compose.yaml and does not check if the version is invalid. 

This error needs to be handled. For ex, here it should throw an error saying the version is invalid and should **not** try to reset with an invalid version.

#### Possible fixes

A quick fix would be to check if the response body is `404: Not Found`. 

But, a better and robust fix would be to have a central validator with the `MesheryCtlConfig` struct in the `config.go` file. This would be helpful if we require version validation for other commands.

The validation could be done using Regex.
