### ISSUE TITLE
[mesheryctl] [child] platform support for Kubernetes in `system start`(`platform: kubernetes`)

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/meshery#2308]
See Epic #2307 for context and further description of this issue.

**Current Behavior**
`mesheryctl system start` compiles the `docker-compose.yaml` file without consideration of the context's platform type.

**Desired Behavior**
`mesheryctl system start` should check the value of `platform` key of the current-context and deploy accordingly as shown in the example scenario below-

`config.yaml` file-

```YAML
user@computer:~/.meshery$ cat config.yaml
contexts:
  local:
    endpoint: http://localhost:9081
    token:
      name: Default
      location: auth.json
    platform: kubernetes # platform is Kubernetes
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-nginx-sm
    channel: stable
    version: v0.4.20

current-context: local
tokens: {}
```

Since the platform is “kubernetes”, the `system start` command should not by default compile the `docker-compose.yaml` file and run Meshery on Docker but instead should deploy on to Kubernetes. 

**Implementation**
`mesheryctl` already "pulls" the platform type from the `config.yaml` file in the `config.go` file-

https://github.com/layer5io/meshery/blob/b0c1a7fa39dd0456f9112be068d2601bfe17d465/mesheryctl/internal/cli/root/config/config.go#L31-L38

`system start` should check this key and deploy Meshery to Docker or Kubernetes accordingly.

Kubernetes deployment files will be downloaded from [/install/deployment_yamls/k8s](https://github.com/layer5io/meshery/tree/master/install/deployment_yamls/k8s) (a configurable, but default location) alongside the docker-compose.yaml (see Issue #2309 - [mesheryctl] [child] platform support during “bash script” installation).

It should compile locally available kubernetes deployment files and apply those to the cluster.

1. Implement Meshery deployment to Kubernetes using [go-cilent from Kubernetes](https://github.com/kubernetes/client-go). This can be implemented by leveraging functions from [MeshKit](https://github.com/layer5io/meshkit).

_Do not use system-level calls to a bash script like `$ kubectl apply -f <deployment YAML files>. Do not use Helm._

2. Compile the Kubernetes manifests each time the user invokes a `system` command, which means that the config.yaml file should be read and Kubernetes manifest files should be written to disk. Specifically in the `~/.meshery` app folder under `/install`.
(default: `~/.meshery/install/<k8s-deploy-xx>.yaml`) - Use a global variable to reference this location.(similar to the `docker-compose.yaml` file)

**Acceptance Tests**
1. `mesheryctl system start` applies Kubernetes manifests to cluster specified in the current context.

1. Current context is used unless the user overrides with `--context` as a one-time flag to specify a different target cluster.

1. Maintain idempotency - Multiple executions of `system start` to the same Kubernetes cluster has no adverse affect. See `system update` for considerations.

1. Fresh copies of the K8s manifest files should be retrieved from the globally configured registry location (default: github.com/layer5io/meshery/install……  releases/tags/vx.x.x).

1. Retrieved copies of K8s manifest files should be of the same version number as `mesheryctl`.
