### ISSUE TITLE
[mesheryctl] Token location should be in section dedicated to tokens

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2435]
#### Description
The following is an example of the v0.5.0-beta-4 default context, created by mesheryctl:

```
contexts:
  local:
    endpoint: http://localhost:9081
    token:
      name: Default
      location: auth.json
    platform: docker
    adapters:
    - meshery-istio
    - meshery-linkerd
    - meshery-consul
    - meshery-octarine
    - meshery-nsm
    - meshery-kuma
    - meshery-cpx
    - meshery-osm
    - meshery-traefik-mesh
    channel: stable
current-context: local
```

#### Expected Behavior
`      location: auth.json` should be in a dedicated `token` section of the meshconfig, like so:
```
contexts:
   <context1-name>:
	endpoint: <url to meshery server rest api>
	token: <name of token variable in this config file>
platform: <type of platform: ”docker” or “kubernetes”> 
# Future: specify type of kubernetes (e.g. eks)
adapters: <collection of names of service mesh adapters: “istio”,“linkerd”,”consul”,”nginx-sm”,”octarine”,”tanzu-sm”,”citrix-sm”,”kuma”,”osm”,”nsm”> 
# Future: ”app-mesh”,”traefik-mesh”
   <context2-name>:
	endpoint: <url to meshery server rest api>
	token: <name of token variable in this config file>
platform: <type of platform: ”docker” or “kubernetes”>
current-context: <context name>
tokens:
- name: <token1-name>
  location: <token-location>
- name: <token2-name>
  value: <token-value> 
  # Future: allow embedding of token certificate
```

See "[meshery config template](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.2oq40t5wa4bu)" section of the Meshery CLI & Documentation doc for more details.

Tokens are to be independently controlled outside of the lifecycle of a given context.

Token name is to remain under the named context section to provide a "foreign key" to the token referenced in the token section.

```
    token:
      name: Default
```

#### Environment:
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

<!-- Optional
