### ISSUE TITLE
[Platform] GKE: MeshKit-based adapters not authenticating to Kube API

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#2440]
#### Description
Meshery Adapter for Istio and other MeshKit-based adapters are not available on @rwong2888's system. He has the following environment:

- a gke cluster was instantiated with https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/private-cluster

#### Expected Behavior
Meshery Adapter for Istio should be available.

#### Screenshots/Logs
[mesheryctl.log](https://github.com/layer5io/meshery/files/6025580/mesheryctl.log)
![image (3)](https://user-images.githubusercontent.com/7570704/108779297-4285ae00-752c-11eb-9207-7dc3181ed900.png)

#### Environment:
- Host OS: macOS
- Meshery Version: v0.5.0-rc-3
- Kubernetes Version: GKE private cluster
- Browser: 

#### To Reproduce
@rwong2888 has run the following sequence of commands:

```
10687  mesheryctl system stop
10688  docker rm -f $(docker ps -aq)
10689  docker ps
10690  docker ps -aq
10691  rm -rf ~/.meshery
10692  rm ~/.kube/config
10693  gcloud container clusters get-credentials playground --region us-east4
10694  mesheryctl system start
10695  mesheryctl system config gke --token ~/Downloads/auth.json
10696  mv ~/.meshery/kubeconfig.yaml ~/.kube/config
```

#### Reference
Conversation - https://istio.slack.com/archives/C01NS1FMHSR/p1614025599030300

**Comment by kumarabd** [comment]
@hexxdump will you be able to check this one?

**Comment by kumarabd** [comment]
@leecalcote Can you share with us the logs here?

**Comment by leecalcote** [comment]
[mesheryctl.log](https://github.com/layer5io/meshery/files/6030831/mesheryctl.log)

**Comment by hexxdump** [comment]
Attaching more logs from Raymond's setup:

[mesheryctl-2021.02.24.11.02.log](https://github.com/layer5io/meshery/files/6040975/mesheryctl-2021.02.24.11.02.log)
[mesheryctl-2021.02.24.10.59.log](https://github.com/layer5io/meshery/files/6040976/mesheryctl-2021.02.24.10.59.log)

I had offline chat with Raymond, I have confirmed with him that the "mesheryctl system config gke -t <auth.json>" is generating kubeconfig.yaml as expected. No errors thrown from the GKE script. kubeconfig.yaml also seems to be fine.

```
❯ cat kubeconfig.yaml                                                                                                                                                                                                                   [11:16:02]
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxx
    server: https://xxxx
  name: gke_forbes-development_us-east4_playground
contexts:
- context:
    cluster: gke_forbes-development_us-east4_playground
    namespace: default
    user: sa-meshery-ligmkchm-default-gke_forbes-development_us-east4_playground
  name: sa-meshery-ligmkchm-default-gke_forbes-development_us-east4_playground
current-context: sa-meshery-ligmkchm-default-gke_forbes-development_us-east4_playground
kind: Config
preferences: {}
users:
- name: sa-meshery-ligmkchm-default-gke_forbes-development_us-east4_playground
  user:
    token: xxxxx
```

However, the below logs are seen in the latest 'mesheryctl system logs'

from log file1:
```

~/Downloads/mesheryctl-2021.02.24.10.59.log:40: [33;1mmeshery-octarine_1      |[0m time="2021-02-24T15:30:53Z" level=error msg="unable to create a new Octarine client: No Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:126: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:53Z" level=error msg="unable to create client set: no Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:127: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:53Z" level=error msg="unable to scan Kubernetes: unable to create client set: no Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:129: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:53Z" level=error msg="Error creating a mesh client.: rpc error: code = Unknown desc = unable to create a new Octarine client: No Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:134: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:53Z" level=error msg="unable to create client set: no Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:135: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:53Z" level=error msg="unable to create client set: no Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:138: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:55Z" level=error msg="unable to create client set: no Auth Provider found for name \"gcp\""
~/Downloads/mesheryctl-2021.02.24.10.59.log:139: [34;1mmeshery_1               |[0m time="2021-02-24T15:30:55Z" level=error msg="unable to ping Kubernetes: unable to create client set: no Auth Provider found for name \"gcp\""
```

from log file2:
```
~/Downloads/mesheryctl-2021.02.24.11.02.log:7: [33mmeshery-cpx_1           |[0m time="2021-02-24T16:00:29Z" level=error msg="unable to create a new cpx client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
~/Downloads/mesheryctl-2021.02.24.11.02.log:21: [36;1mmeshery-nsm_1           |[0m time="2021-02-24T16:00:29Z" level=error msg="unable to create a new NSM client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
~/Downloads/mesheryctl-2021.02.24.11.02.log:23: [33;1mmeshery-octarine_1      |[0m time="2021-02-24T16:00:29Z" level=error msg="unable to create a new Octarine client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
~/Downloads/mesheryctl-2021.02.24.11.02.log:29: [32;1mmeshery-osm_1           |[0m time="2021-02-24T16:00:29Z" level=error msg="unable to create a new osm client: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
~/Downloads/mesheryctl-2021.02.24.11.02.log:104: [34;1mmeshery_1               |[0m time="2021-02-24T16:00:29Z" level=error msg="unable to load in-cluster kubeconfig: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"

```

@kumarabd mentioned that he will take a look at the environment variable issue.
