### ISSUE TITLE
[Kubernetes] Cannot ping adapters when meshery deployed in Kubernetes

### ISSUE THREAD

**Issue by piyushsingariya** [layer5io/meshery#2603]
#### Description
When Meshery is deployed in Kubernetes. All the adapters are in running state still, Meshery is unable to ping to multiple adapters.
Only 3 adapters seem active: CPX, OSM, NSM
_(Attaching Screenshots)_
![image](https://user-images.githubusercontent.com/50979887/112639899-ce119800-8e66-11eb-8ad0-5ae533b98e77.png)
![image](https://user-images.githubusercontent.com/50979887/112639953-df5aa480-8e66-11eb-948e-ae1b884df8d9.png)

#### Expected Behavior
Meshery should be able to find and ping all the adapter when deployed in Kubernetes

#### Environment:
- Meshery Version: v0.5.0
- Kubernetes Version: v1.20.5
- Host OS: Linux/Ubuntu

#### To Reproduce
1. Deploy Meshery in k8s cluster
2. Port-forward meshery and go to localhost:9081
3. Try pinging any adapter except the mentioned

**Comment by navendu-pottekkat** [comment]
@piyushsingariya are you able to ping to the adapters that are shown in the UI?

**Comment by navendu-pottekkat** [comment]
If yes, then this could be a problem with those adapters...

// @abhishekkumkar @mgfeller

**Comment by piyushsingariya** [comment]
> @piyushsingariya are you able to ping to the adapters that are shown in the UI?

I can ping only three of them(the ones mentioned above)

**Comment by piyushsingariya** [comment]
![image](https://user-images.githubusercontent.com/50979887/112667215-02934d00-8e83-11eb-8065-270bac9cac04.png)
@navendu-pottekkat with adapters clearly being active, this is a problem from Meshery's side.

**Comment by leecalcote** [comment]
This issue is only affecting adapters based on MeshKit, it seems.

**Comment by anirudhjain75** [comment]
Ohh Yea I have already created an issue for this. But my one was specific to gcloud. Its stale. Lemme retest and push

**Comment by anirudhjain75** [comment]
This issue is still pending. I've attached a SS. Using GKE Cluster
![image](https://user-images.githubusercontent.com/14249589/112939975-0b697480-914a-11eb-9715-e892af33edf2.png)

**Comment by leecalcote** [comment]
@kumarabd please consider this issue a high priority.

**Comment by mgfeller** [comment]
using minikube, with ingress addon enabled

```
❯ cat ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meshery-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: meshery
            servicePort: 9081
```

Note: ingress yaml given in https://docs.meshery.io/installation/platforms/kubernetes#using-kubernetes-manifests should be updated.
