### ISSUE TITLE
Add local "Application" Pattern capability

### ISSUE THREAD

**Issue by utkarsh-pro** [layer5io/meshery#2901]
#### Current Behavior
Right now meshery server has only one trait. 

#### Desired Behavior
"Application" specific OAM traits and workload definition needs to be added in meshery server in order to add those capabilities.

An `application` pattern may look like:
```yaml
id: f18a7e16-9324-407a-9ab6-858c56b8ad5e # Unique ID for the pattern
name: ApplicationPattern # Name of the pattern file
version: 0.0.1-alpha # Pattern file version
services:
  myapp: # Application name (Not neccesarily a Kubernetes service)
    type: Application
    namespace: linkerd-test
    mesh: linkerd # Required only if multiple meshes are in the cluster
    settings:
      replicas: 1 # Number of replicas to run 
      # (Will be important if cluster has no service mesh installed)
      containers:
        - name: myapp # Name of the container
          image: utkarsh23/meshy:v5 # Image (only docker hub images for now)
          ports:
          - name: http
            containerPort: 8080
          resources: # Optional
            requests:
              memory: 32Mi
              cpu: 5m
    traits:
      strategy: # Deployment strategy - Can be canary or blue green
        canary:
          steps:
          - setWeight: 5 # Redirect 5% traffic to the canary
          - pause: {duration: 60} # Wait for 60s before promoting to next step'
          
          - setWeight: 40
          - pause: {duration: 10}
```

#### Acceptance Tests
1. New Trait Definition must be added along with their JSON schema
2. New Workload Definition must be added along with their JSON schema

#### Mockups
Please refer the `oam` directory for examples.
