### ISSUE TITLE
Docs: Provide inline reference to heading / section anchor

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#468]
**Current State:**
Anytime an h1, h2, h3 (#, ##, ###) and so on is used in the docs, an inner-page, anchor tag to link to that specific section of the docs is made available in the righthand nav bar.

**Desired State:**
Enhance the theme to ensure links to anchor tags are made available adjacent to the heading name and represented as a link / chain / clip icon for available to readers' for quick reference.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
This is similar to what we're looking for, but it would ideally have a chain-looking icon, not a paragraph symbol - https://github.com/bryanbraun/anchorjs

**Comment by firstladymb** [comment]
Thanks! I swapped the paragraph for a chain in my branch and made it copy
to clipboard. I'm wanting to add a tooltip that says "copied" after you
click the button (or falls back to changing the window location if the
browser doesn't allow copy to clipboard). I went down the rabbit hole
exploring tooltip options, so if you already have one you like or
recommend, I'm happy to give that one a try!

Marybeth Alexander
(305) 393-5982

**Comment by leecalcote** [comment]
@Silvyre would you mind introducing @firstladymb to the rich tooltip used on meshery.io, so that she might consider reusing it?

**Comment by RafaelUngar** [comment]
Sure!

Meshery.io adds tooltips in HTML like so:
```html
<div class="tooltip">
  ...
  <span class="tooltiptext">...</span>
</div>
```
and styles them like so (from [meshery/materialize.css](https://github.com/meshery/meshery/blob/master/assets/css/materialize.css#L2960)):
```css
.tooltip {
  position: relative;
  display: inline-block;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 200px;
  background-color:var(--main-dark-grey);
  color:aliceblue ;
  text-align: center;
  border-radius: 6px;
  padding: 10px;

  /* Position the tooltip */
  position: absolute;
  z-index: 1;
  top: 100%;
  left: 50%; 
  margin-left: -60px;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
}
```

Mouse over some of the links on [meshery.io/landscape](https://meshery.io/landscape/) to see the tooltips in action. (The Meshery may require additional styling from [Materialize](https://materializecss.com/) to reproduce the effect exactly as it appears on the Meshery site, however.)
