### ISSUE TITLE
meshery: Update meshery results export to follow SMP

### ISSUE THREAD

**Issue by nveenjain** [layer5io/meshery#896]
**Description**

Currently when you export a result, then a yaml file is downloaded. This file doesn't support SMP.
It only follows SMP partially... 

**Expected Behavior**

Exported yaml should follow SMP.

**Screenshots**
![image](https://user-images.githubusercontent.com/22762181/80262975-cc66af80-86ac-11ea-8bb6-349340a9abb9.png)
Click on download button

**Environment:**
 - OS: Any
 - Browser: ANy
 - Version: Latest
 - Device: Any
---
[Optional] **To Reproduce**
1. Create a performance result for any mesh
2. Click on results
3. Scroll down to any result, select it and click on download on top bar
4. Downloaded file doesn't follow SMPS.

[Optional] **Additional Context**

Currently results are downloaded in this format:-

```yaml
start_time: 2020-04-02T03:43:59.524931729+05:30
end_time: 2020-04-02T03:44:09.526222812+05:30
exp_uuid: assafs-XXXX-XXXX-XXXX-XXXXXXXX
endpoint_url: http://10.0.2.15:31380/productpage
env:
  kubernetes: v1.17.3
client:
  connections: 5
  rps: 1232.3408945620827
  latencies_ms:
    min: 0.000133302
    average: 0.004056244610385397
    p50: 0.002047835195530726
    p90: 0.009221491228070174
    p99: 0.025705645161290324
    max: 0.243865731
metrics: {}
```
This result should follow https://github.com/layer5io/service-mesh-performance-specification/blob/master/smps.yaml
