### ISSUE TITLE
[Docs] Advanced Installation section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#966]
**Current State:**
Users that desire to control the version of Meshery that they deploy don't have a guide for how to so so.

**Desired State:**
The docs should have an Advanced Installation section, containing an expansion of the following: 

_Users can control the specific container image (version) of Meshery that they would like to run by editing their local `~/.meshery/meshery.yaml` file.
In the line with the `meshery` container image, instead of leaving the implicit `:latest` tag behind `image: layer5/meshery`, users will instead identify a specific image tag like so:_
```
version: '3'
services:
  meshery:
    image: layer5/meshery:eeeb528f8c6ac59ff5d435a857ff68d00046cf0e
    labels:
      - "com.centurylinklabs.watchtower.enable=true
```

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
